### ISSUE TITLE
24hr times in Notifications

### ISSUE THREAD

**Issue by MisterTickle** [MathijsNL/WhatsappTime#1] opened 2022-04-13 09:35 UTC
Thanks for this brilliant extension to fix the appalling issue. I'm seeing 12hr clock times in the pop-up notifications in Chrome when I have an incoming message. Is this something that this extension could also fix, please?

**Comment by MathijsNL** [comment] 2022-04-13 10:44
Depends on how this can be fixed. If the notification has to be modified the extension would need additional permissions for all notifications which is not ideal.

I also think WhatsApp will fix this in the near future, so if there is an easy fix we can maybe do it but otherwise I think we should just accept the brief disturbance caused by the notification.

Edit:
It looks like notifications are handled from bootstrap_qr.*.js, which is a webpack. Hard to modify, and prone to errors to make it the same for all users. So modifying them before the notifications are generated is (at least for me) not feasible.

I think adding more permissions to alter notifications could maybe be done, but for how long notifications are shown it's probably not worth it. If you have any ideas let me know.

**Comment by MisterTickle** [comment] 2022-04-13 21:25
Fair enough! I didn't know enough about how notifications work in Chrome - I agree with you that it's much harder than just a simple tweak. Thought I'd ask the question though.

**Comment by MathijsNL** [comment] 2022-04-16 00:54
I will close this issue for now, if someone wants to work on this they can create a pull request or a new issue.

**Closed as completed by MathijsNL** 2022-04-16 00:54 UTC
Labels: enhancement
